language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
before_script: rustup component add clippy
script:
  - if [ "${TRAVIS_RUST_VERSION}" != "nightly" ]; then
    cargo clippy --all-targets --all-features -- -D warnings
    fi
  - cargo test --all --verbose
matrix:
  allow_failures:
    - rust: nightly
