language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
install: cargo build --all --verbose
before_script: rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --all --verbose
matrix:
  allow_failures:
    - rust: nightly
