[package]
name = "timeline"
version = "0.1.3"
authors = ["Spaceface16518 <33424649+Spaceface16518@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"
name = "timeline"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
structopt = "0.2"
serde_json = "1"
bson = "0.13"
regex = "1.1"
