wrap_comments = true
max_width = 80
reorder_impl_items = true
merge_imports = true
reorder_imports = true
reorder_modules = true
condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
format_macro_matchers = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
force_multiline_blocks = true
normalize_comments = true
use_field_init_shorthand = true
format_doc_comments = true
